services:
  - type: web
    name: recursion-visualizer
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y graphviz
      pip install -r requirements.txt
    startCommand: gunicorn app:app